# Generated by Django 5.1.1 on 2024-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
